=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SubfiPay::CheckoutTemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutTemplatesApi' do
  before do
    # run before each test
    @api_instance = SubfiPay::CheckoutTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutTemplatesApi' do
    it 'should create an instance of CheckoutTemplatesApi' do
      expect(@api_instance).to be_instance_of(SubfiPay::CheckoutTemplatesApi)
    end
  end

  # unit tests for create_checkout_template
  # Create a new checkout template
  # @param x_api_version 
  # @param checkout_template_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutTemplateResponse]
  describe 'create_checkout_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_render_token
  # Create a render token for checkout template
  # @param x_api_version 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [TokenResponse]
  describe 'create_render_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_checkout_template
  # Retrieve a checkout template by ID
  # @param x_api_version 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutTemplateResponse]
  describe 'get_checkout_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_checkout_templates
  # List all checkout templates
  # @param x_api_version 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :account_id 
  # @return [ListCheckoutTemplatesResponse]
  describe 'list_checkout_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
