=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SubfiPay::ExternalAccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExternalAccountsApi' do
  before do
    # run before each test
    @api_instance = SubfiPay::ExternalAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalAccountsApi' do
    it 'should create an instance of ExternalAccountsApi' do
      expect(@api_instance).to be_instance_of(SubfiPay::ExternalAccountsApi)
    end
  end

  # unit tests for create_external_account
  # Create an external account
  # @param x_api_version 
  # @param x_account_id 
  # @param external_account_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ExternalAccountResponse]
  describe 'create_external_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_external_account
  # Retrieve an external account by ID
  # @param x_api_version 
  # @param x_account_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ExternalAccountResponse]
  describe 'get_external_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_external_accounts
  # List all external accounts
  # @param x_api_version 
  # @param x_account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListExternalAccountsResponse]
  describe 'list_external_accounts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
