=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SubfiPay::FraudRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FraudRulesApi' do
  before do
    # run before each test
    @api_instance = SubfiPay::FraudRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FraudRulesApi' do
    it 'should create an instance of FraudRulesApi' do
      expect(@api_instance).to be_instance_of(SubfiPay::FraudRulesApi)
    end
  end

  # unit tests for create_fraud_rule
  # Create a Fraud Rule
  # @param x_api_version 
  # @param fraud_rule_create_request 
  # @param [Hash] opts the optional parameters
  # @return [FraudRuleResponse]
  describe 'create_fraud_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_fraud_rule
  # Delete a Fraud Rule by ID
  # @param x_api_version 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_fraud_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_fraud_rules
  # List all fraud rules
  # @param x_api_version 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListFraudRulesResponse]
  describe 'list_fraud_rules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
