=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SubfiPay::SetupIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SetupIntentsApi' do
  before do
    # run before each test
    @api_instance = SubfiPay::SetupIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetupIntentsApi' do
    it 'should create an instance of SetupIntentsApi' do
      expect(@api_instance).to be_instance_of(SubfiPay::SetupIntentsApi)
    end
  end

  # unit tests for create_setup_intent
  # Create a new setup intent
  # @param x_api_version 
  # @param x_account_id 
  # @param setup_intent_create_request 
  # @param [Hash] opts the optional parameters
  # @return [SetupIntentResponse]
  describe 'create_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
