=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SubfiPay::SubscriptionPlansApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionPlansApi' do
  before do
    # run before each test
    @api_instance = SubfiPay::SubscriptionPlansApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionPlansApi' do
    it 'should create an instance of SubscriptionPlansApi' do
      expect(@api_instance).to be_instance_of(SubfiPay::SubscriptionPlansApi)
    end
  end

  # unit tests for create_subscription_plan
  # Create a new subscription plan
  # @param x_api_version 
  # @param x_account_id 
  # @param subscription_plan_create_request 
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionPlanResponse]
  describe 'create_subscription_plan test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_subscription_plan
  # Retrieve a subscription plan by ID
  # @param x_api_version 
  # @param x_account_id 
  # @param id The ID of the subscription plan to retrieve
  # @param [Hash] opts the optional parameters
  # @return [SubscriptionResponse]
  describe 'get_subscription_plan test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_subscription_plans
  # List all subscription plans
  # @param x_api_version 
  # @param x_account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @return [ListSubscriptionsResponse]
  describe 'list_subscription_plans test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
