=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'cgi'

module SubfiPay
  class OriginsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create a new origin
    # @param x_api_version [String] 
    # @param origin_create_request [OriginCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [OriginResponse]
    def create_origin(x_api_version, origin_create_request, opts = {})
      data, _status_code, _headers = create_origin_with_http_info(x_api_version, origin_create_request, opts)
      data
    end

    # Create a new origin
    # @param x_api_version [String] 
    # @param origin_create_request [OriginCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(OriginResponse, Integer, Hash)>] OriginResponse data, response status code and response headers
    def create_origin_with_http_info(x_api_version, origin_create_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OriginsApi.create_origin ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling OriginsApi.create_origin"
      end
      # verify the required parameter 'origin_create_request' is set
      if @api_client.config.client_side_validation && origin_create_request.nil?
        fail ArgumentError, "Missing the required parameter 'origin_create_request' when calling OriginsApi.create_origin"
      end
      # resource path
      local_var_path = '/origins'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end
      header_params[:'X-Api-Version'] = x_api_version

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(origin_create_request)

      # return_type
      return_type = opts[:debug_return_type] || 'OriginResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key']

      new_options = opts.merge(
        :operation => :"OriginsApi.create_origin",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OriginsApi#create_origin\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List all origins
    # @param x_api_version [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @return [ListOriginsResponse]
    def list_origins(x_api_version, opts = {})
      data, _status_code, _headers = list_origins_with_http_info(x_api_version, opts)
      data
    end

    # List all origins
    # @param x_api_version [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @return [Array<(ListOriginsResponse, Integer, Hash)>] ListOriginsResponse data, response status code and response headers
    def list_origins_with_http_info(x_api_version, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OriginsApi.list_origins ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling OriginsApi.list_origins"
      end
      # resource path
      local_var_path = '/origins'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Api-Version'] = x_api_version

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListOriginsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key']

      new_options = opts.merge(
        :operation => :"OriginsApi.list_origins",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OriginsApi#list_origins\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
