=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'cgi'

module SubfiPay
  class ProductsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create a new product
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param product_create_request [ProductCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [ProductResponse]
    def create_product(x_api_version, x_account_id, product_create_request, opts = {})
      data, _status_code, _headers = create_product_with_http_info(x_api_version, x_account_id, product_create_request, opts)
      data
    end

    # Create a new product
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param product_create_request [ProductCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ProductResponse, Integer, Hash)>] ProductResponse data, response status code and response headers
    def create_product_with_http_info(x_api_version, x_account_id, product_create_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ProductsApi.create_product ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling ProductsApi.create_product"
      end
      # verify the required parameter 'x_account_id' is set
      if @api_client.config.client_side_validation && x_account_id.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_id' when calling ProductsApi.create_product"
      end
      # verify the required parameter 'product_create_request' is set
      if @api_client.config.client_side_validation && product_create_request.nil?
        fail ArgumentError, "Missing the required parameter 'product_create_request' when calling ProductsApi.create_product"
      end
      # resource path
      local_var_path = '/products'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end
      header_params[:'X-Api-Version'] = x_api_version
      header_params[:'X-Account-Id'] = x_account_id

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(product_create_request)

      # return_type
      return_type = opts[:debug_return_type] || 'ProductResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key']

      new_options = opts.merge(
        :operation => :"ProductsApi.create_product",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProductsApi#create_product\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List all products
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @return [ListProductsResponse]
    def list_products(x_api_version, x_account_id, opts = {})
      data, _status_code, _headers = list_products_with_http_info(x_api_version, x_account_id, opts)
      data
    end

    # List all products
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page The page of results to retrieve.
    # @option opts [Integer] :per_page Number of results per page.
    # @return [Array<(ListProductsResponse, Integer, Hash)>] ListProductsResponse data, response status code and response headers
    def list_products_with_http_info(x_api_version, x_account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ProductsApi.list_products ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling ProductsApi.list_products"
      end
      # verify the required parameter 'x_account_id' is set
      if @api_client.config.client_side_validation && x_account_id.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_id' when calling ProductsApi.list_products"
      end
      # resource path
      local_var_path = '/products'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Api-Version'] = x_api_version
      header_params[:'X-Account-Id'] = x_account_id

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ListProductsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key']

      new_options = opts.merge(
        :operation => :"ProductsApi.list_products",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProductsApi#list_products\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update a product by ID
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param id [String] The ID of the product to update
    # @param product_update_request [ProductUpdateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [ProductResponse]
    def update_product(x_api_version, x_account_id, id, product_update_request, opts = {})
      data, _status_code, _headers = update_product_with_http_info(x_api_version, x_account_id, id, product_update_request, opts)
      data
    end

    # Update a product by ID
    # @param x_api_version [String] 
    # @param x_account_id [String] 
    # @param id [String] The ID of the product to update
    # @param product_update_request [ProductUpdateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ProductResponse, Integer, Hash)>] ProductResponse data, response status code and response headers
    def update_product_with_http_info(x_api_version, x_account_id, id, product_update_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ProductsApi.update_product ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling ProductsApi.update_product"
      end
      # verify the required parameter 'x_account_id' is set
      if @api_client.config.client_side_validation && x_account_id.nil?
        fail ArgumentError, "Missing the required parameter 'x_account_id' when calling ProductsApi.update_product"
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ProductsApi.update_product"
      end
      # verify the required parameter 'product_update_request' is set
      if @api_client.config.client_side_validation && product_update_request.nil?
        fail ArgumentError, "Missing the required parameter 'product_update_request' when calling ProductsApi.update_product"
      end
      # resource path
      local_var_path = '/products/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end
      header_params[:'X-Api-Version'] = x_api_version
      header_params[:'X-Account-Id'] = x_account_id

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(product_update_request)

      # return_type
      return_type = opts[:debug_return_type] || 'ProductResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['X-Api-Key']

      new_options = opts.merge(
        :operation => :"ProductsApi.update_product",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProductsApi#update_product\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
