=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::BillingAddress
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::BillingAddress do
  let(:instance) { SubfiPay::BillingAddress.new }

  describe 'test an instance of BillingAddress' do
    it 'should create an instance of BillingAddress' do
      expect(instance).to be_instance_of(SubfiPay::BillingAddress)
    end
  end

  let(:attributes) { %w[first_name last_name email phone address_line1 address_line2 city state country postal_code] }

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
