=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubFiPay::CardProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubFiPay::CardProfile do
  let(:instance) { SubFiPay::CardProfile.new }

  describe 'test an instance of CardProfile' do
    it 'should create an instance of CardProfile' do
      expect(instance).to be_instance_of(SubFiPay::CardProfile)
    end
  end

  let(:attributes) { %w[avs_check avs_check_message brand cvc_check cvc_check_message exp_month exp_year funding last4 three_d_secure_supported token] }

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
