=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::ChargePaymentMethodCardProfile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::ChargePaymentMethodCardProfile do
  let(:instance) { BckbnPay::ChargePaymentMethodCardProfile.new }

  describe 'test an instance of ChargePaymentMethodCardProfile' do
    it 'should create an instance of ChargePaymentMethodCardProfile' do
      expect(instance).to be_instance_of(BckbnPay::ChargePaymentMethodCardProfile)
    end
  end

  let(:fields) { %i[avs_check avs_check_message brand cvc_check cvc_check_message exp_month exp_year funding last4 three_d_secure_supported token] }

  it 'should work' do
    fields.each do |field|
      expect(instance).to respond_to(field)
    end
  end
end
