=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubFiPay::ChargeResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubFiPay::ChargeResponse do
  let(:instance) { SubFiPay::ChargeResponse.new }

  describe 'test an instance of ChargeResponse' do
    it 'should create an instance of ChargeResponse' do
      expect(instance).to be_instance_of(SubFiPay::ChargeResponse)
    end
  end

  let(:attributes) { %w[amount description payment_method_id connected_account_id immediate_capture id captured_at failure_reason account_id payment_method processor_id state created_at] }

  describe "encoding" do
    it "should be UTF-8" do
      instance.processor_id = "foobar"
      expect(instance.processor_id.encoding.to_s).to eq("UTF-8")
    end
  end

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
