=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::ChargeResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::ChargeResponse do
  let(:instance) { SubfiPay::ChargeResponse.new }

  describe 'test an instance of ChargeResponse' do
    it 'should create an instance of ChargeResponse' do
      expect(instance).to be_instance_of(SubfiPay::ChargeResponse)
    end
  end

  let(:attributes) { %w[amount customer_id description metadata payment_intent_id payment_method_id id account_id state succeeded_at created_at updated_at] }

  describe "encoding" do
    it "should be UTF-8" do
      instance.description = "a charge"
      expect(instance.description.encoding.to_s).to eq("UTF-8")
    end
  end

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
