=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::ExternalAccountCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::ExternalAccountCreateRequest do
  let(:instance) { SubfiPay::ExternalAccountCreateRequest.new }

  describe 'test an instance of ExternalAccountCreateRequest' do
    it 'should create an instance of ExternalAccountCreateRequest' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SubfiPay::ExternalAccountCreateRequest)
    end
  end

  describe 'test attribute "external_account"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
