=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::ListPaymentIntentsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::ListPaymentIntentsResponse do
  let(:instance) { BckbnPay::ListPaymentIntentsResponse.new }

  describe 'test an instance of ListPaymentIntentsResponse' do
    it 'should create an instance of ListPaymentIntentsResponse' do
      expect(instance).to be_instance_of(BckbnPay::ListPaymentIntentsResponse)
    end
  end

  let(:attributes) { %w[data meta] }

  describe "encoding" do
    it "should be UTF-8" do
      instance.data = "data"
      expect(instance.data.encoding.to_s).to eq("UTF-8")
    end
  end

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
