=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::ListRenderTemplatesResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::ListRenderTemplatesResponse do
  let(:instance) { SubfiPay::ListRenderTemplatesResponse.new }

  describe 'test an instance of ListRenderTemplatesResponse' do
    it 'should create an instance of ListRenderTemplatesResponse' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SubfiPay::ListRenderTemplatesResponse)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "meta"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
