=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::PaymentMethodsPostRequestPaymentMethod
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::PaymentMethodsPostRequestPaymentMethod do
  let(:instance) { BckbnPay::PaymentMethodsPostRequestPaymentMethod.new }

  describe 'test an instance of PaymentMethodsPostRequestPaymentMethod' do
    it 'should create an instance of PaymentMethodsPostRequestPaymentMethod' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(BckbnPay::PaymentMethodsPostRequestPaymentMethod)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "billing_address_attributes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
