=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::PaymentMethodResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::PaymentMethodResponse do
  let(:instance) { BckbnPay::PaymentMethodResponse.new }

  describe 'test an instance of PaymentMethodResponse' do
    it 'should create an instance of PaymentMethodResponse' do
      expect(instance).to be_instance_of(BckbnPay::PaymentMethodResponse)
    end
  end

  let(:attributes) { %w[type billing_address card_profile bank_account_profile id created_at updated_at metadata partner_id sub_merchant_id] }

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
