=begin
# Bckbn Pay API

# API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::PaymentMethodsPostRequestPaymentMethodCardProfileAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::PaymentMethodsPostRequestPaymentMethodCardProfileAttributes do
  let(:instance) { BckbnPay::PaymentMethodsPostRequestPaymentMethodCardProfileAttributes.new }

  describe 'test an instance of PaymentMethodsPostRequestPaymentMethodCardProfileAttributes' do
    it 'should create an instance of PaymentMethodsPostRequestPaymentMethodCardProfileAttributes' do
      expect(instance).to be_instance_of(BckbnPay::PaymentMethodsPostRequestPaymentMethodCardProfileAttributes)
    end
  end

  describe 'test attribute "encrypted_card_number"' do
    it 'should respond to encrypted_card_number' do
      expect(instance.respond_to?(:encrypted_card_number)).to eq(true)
    end
  end

  describe 'test attribute "exp_month"' do
    it 'should respond to exp_month' do
      expect(instance.respond_to?(:exp_month)).to eq(true)
    end
  end

  describe 'test attribute "exp_year"' do
    it 'should respond to exp_year' do
      expect(instance.respond_to?(:exp_year)).to eq(true)
    end
  end

  describe 'test attribute "cvc"' do
    it 'should respond to cvc' do
      expect(instance.respond_to?(:cvc)).to eq(true)
    end
  end
end
