=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes do
  let(:instance) { BckbnPay::PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes.new }

  describe 'test an instance of PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes' do
    it 'should create an instance of PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes' do
      expect(instance).to be_instance_of(BckbnPay::PaymentMethodsPostRequestPaymentMethodBankAccountProfileAttributes)
    end
  end

  describe 'test attribute "account_holder_name"' do
    it 'should work' do
      expect(instance.respond_to?(:account_holder_name)).to eq(true)
    end
  end

  describe 'test attribute "bank_name"' do
    it 'should work' do
      expect(instance.respond_to?(:bank_name)).to eq(true)
    end
  end

  describe 'test attribute "account_holder_type"' do
    it 'should work' do
      expect(instance.respond_to?(:account_holder_type)).to eq(true)
    end
  end

  describe 'test attribute "account_type"' do
    it 'should work' do
      expect(instance.respond_to?(:account_type)).to eq(true)
    end
  end

  describe 'test attribute "encrypted_account_number"' do
    it 'should work' do
      expect(instance.respond_to?(:encrypted_account_number)).to eq(true)
    end
  end

  describe 'test attribute "routing_number"' do
    it 'should work' do
      expect(instance.respond_to?(:routing_number)).to eq(true)
    end
  end
end
