=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BckbnPay::Refund
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BckbnPay::Refund do
  let(:instance) { BckbnPay::Refund.new }

  describe 'test an instance of Refund' do
    it 'should create an instance of Refund' do
      expect(instance).to be_instance_of(BckbnPay::Refund)
    end
  end

  let(:fields) { %i[id amount charge_id description failure_reason state created_at] }

  it 'should respond to all fields' do
    fields.each do |field|
      expect(instance).to respond_to(field)
    end
  end
end
