=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::RefundAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::RefundAttributes do
  let(:instance) { SubfiPay::RefundAttributes.new }

  describe 'test an instance of RefundAttributes' do
    it 'should create an instance of RefundAttributes' do
      expect(instance).to be_instance_of(SubfiPay::RefundAttributes)
    end
  end

  let(:attributes) { %w[amount charge_id] }

  describe 'test attributes' do

    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
