=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::RenderTemplateAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::RenderTemplateAttributes do
  let(:instance) { SubfiPay::RenderTemplateAttributes.new }

  describe 'test an instance of RenderTemplateAttributes' do
    it 'should create an instance of RenderTemplateAttributes' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SubfiPay::RenderTemplateAttributes)
    end
  end

  describe 'test attribute "allowed_payment_method_types"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["card", "bank_account"])
      # validator.allowable_values.each do |value|
      #   expect { instance.allowed_payment_method_types = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "origin_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
