=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::SetupIntentCreateAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::SetupIntentCreateAttributes do
  let(:instance) { SubfiPay::SetupIntentCreateAttributes.new }

  describe 'test an instance of SetupIntentCreateAttributes' do
    it 'should create an instance of SetupIntentCreateAttributes' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(SubfiPay::SetupIntentCreateAttributes)
    end
  end

  describe 'test attribute "customer_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
