=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::SubscriptionResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::SubscriptionResponse do
  let(:instance) { SubfiPay::SubscriptionResponse.new }

  describe 'test an instance of SubscriptionResponse' do
    it 'should create an instance of SubscriptionResponse' do
      expect(instance).to be_instance_of(SubfiPay::SubscriptionResponse)
    end
  end

  let(:attributes) { %w[connected_account_id customer_id payment_method_id amount interval interval_count next_payment_date state created_at updated_at] }

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
