=begin
#SubFi Pay API

#API for SubFi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::SubscriptionAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::SubscriptionAttributes do
  let(:instance) { SubfiPay::SubscriptionAttributes.new }

  describe 'test an instance of SubscriptionAttributes' do
    it 'should create an instance of SubscriptionAttributes' do
      expect(instance).to be_instance_of(SubfiPay::SubscriptionAttributes)
    end
  end

  let(:attributes) { %w[customer_id payment_method_id amount interval interval_count next_payment_date] }

  describe 'test attributes' do
    it 'should respond to all attributes' do
      attributes.each do |attribute|
        expect(instance).to respond_to(attribute)
      end
    end
  end
end
