=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SubfiPay::WebhookEndpointCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SubfiPay::WebhookEndpointCreateRequest do
  let(:instance) { SubfiPay::WebhookEndpointCreateRequest.new }

  describe 'test an instance of WebhookEndpointCreateRequest' do
    it 'should create an instance of WebhookEndpointCreateRequest' do
      expect(instance).to be_instance_of(SubfiPay::WebhookEndpointCreateRequest)
    end
  end

  describe 'test attribute "webhook_endpoint"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
