=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

# Common files
require 'bckbn_pay/api_client'
require 'bckbn_pay/api_error'
require 'bckbn_pay/version'
require 'bckbn_pay/configuration'

# Models
require 'bckbn_pay/models/balance_transaction_attributes'
require 'bckbn_pay/models/balance_transaction_response'
require 'bckbn_pay/models/bank_account_profile'
require 'bckbn_pay/models/billing_address'
require 'bckbn_pay/models/card_profile'
require 'bckbn_pay/models/charge_attributes'
require 'bckbn_pay/models/charge_response'
require 'bckbn_pay/models/list_balance_transactions_response'
require 'bckbn_pay/models/list_charges_response'
require 'bckbn_pay/models/meta'
require 'bckbn_pay/models/payment_method_attributes'
require 'bckbn_pay/models/payment_method_response'
require 'bckbn_pay/models/refund_attributes'
require 'bckbn_pay/models/refund_response'
require 'bckbn_pay/models/sub_merchant_attributes'
require 'bckbn_pay/models/sub_merchant_response'

# APIs
require 'bckbn_pay/api/balance_transactions_api'
require 'bckbn_pay/api/charges_api'
require 'bckbn_pay/api/payment_methods_api'
require 'bckbn_pay/api/refunds_api'
require 'bckbn_pay/api/sub_merchants_api'

module BckbnPay
  class << self
    # Customize default settings for the SDK using block.
    #   BckbnPay.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
