=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'subfi_pay/api_client'
require 'subfi_pay/api_error'
require 'subfi_pay/version'
require 'subfi_pay/configuration'

# Models
require 'subfi_pay/models/account_attributes'
require 'subfi_pay/models/account_attributes_processor'
require 'subfi_pay/models/account_attributes_processor_configuration'
require 'subfi_pay/models/account_create_request'
require 'subfi_pay/models/account_response'
require 'subfi_pay/models/account_update_attributes'
require 'subfi_pay/models/account_update_request'
require 'subfi_pay/models/bank_account_profile_attributes'
require 'subfi_pay/models/bank_account_profile_response'
require 'subfi_pay/models/billing_address_attributes'
require 'subfi_pay/models/billing_address_response'
require 'subfi_pay/models/bulk_create_payouts_response'
require 'subfi_pay/models/card_profile_attributes'
require 'subfi_pay/models/card_profile_response'
require 'subfi_pay/models/charge_response'
require 'subfi_pay/models/customer_attributes'
require 'subfi_pay/models/customer_create_request'
require 'subfi_pay/models/customer_response'
require 'subfi_pay/models/customer_update_attributes'
require 'subfi_pay/models/customer_update_request'
require 'subfi_pay/models/error_response'
require 'subfi_pay/models/external_account_attributes'
require 'subfi_pay/models/external_account_create_request'
require 'subfi_pay/models/external_account_response'
require 'subfi_pay/models/list_accounts_response'
require 'subfi_pay/models/list_charges_response'
require 'subfi_pay/models/list_customers_response'
require 'subfi_pay/models/list_external_accounts_response'
require 'subfi_pay/models/list_merchants_response'
require 'subfi_pay/models/list_origins_response'
require 'subfi_pay/models/list_payment_intents_response'
require 'subfi_pay/models/list_payment_methods_response'
require 'subfi_pay/models/list_payouts_response'
require 'subfi_pay/models/list_processor_transactions_response'
require 'subfi_pay/models/list_products_response'
require 'subfi_pay/models/list_refunds_response'
require 'subfi_pay/models/list_render_templates_response'
require 'subfi_pay/models/list_subscription_plans_response'
require 'subfi_pay/models/list_subscriptions_response'
require 'subfi_pay/models/list_voids_response'
require 'subfi_pay/models/list_webhook_attempts_response'
require 'subfi_pay/models/list_webhook_endpoints_response'
require 'subfi_pay/models/list_webhook_requests_response'
require 'subfi_pay/models/merchant_attributes'
require 'subfi_pay/models/merchant_create_request'
require 'subfi_pay/models/merchant_response'
require 'subfi_pay/models/meta'
require 'subfi_pay/models/metadata_value'
require 'subfi_pay/models/origin_attributes'
require 'subfi_pay/models/origin_create_request'
require 'subfi_pay/models/origin_response'
require 'subfi_pay/models/payment_intent_confirm_attributes'
require 'subfi_pay/models/payment_intent_confirm_attributes_payment_method'
require 'subfi_pay/models/payment_intent_confirm_request'
require 'subfi_pay/models/payment_intent_create_attributes'
require 'subfi_pay/models/payment_intent_create_request'
require 'subfi_pay/models/payment_intent_response'
require 'subfi_pay/models/payment_intent_update_attributes'
require 'subfi_pay/models/payment_intent_update_request'
require 'subfi_pay/models/payment_method_attributes'
require 'subfi_pay/models/payment_method_response'
require 'subfi_pay/models/payout_bulk_create_attributes'
require 'subfi_pay/models/payout_bulk_create_request'
require 'subfi_pay/models/payout_create_attributes'
require 'subfi_pay/models/payout_create_request'
require 'subfi_pay/models/payout_response'
require 'subfi_pay/models/processor_transaction_response'
require 'subfi_pay/models/product_attributes'
require 'subfi_pay/models/product_create_request'
require 'subfi_pay/models/product_response'
require 'subfi_pay/models/product_update_request'
require 'subfi_pay/models/reconciliation_response'
require 'subfi_pay/models/refund_attributes'
require 'subfi_pay/models/refund_response'
require 'subfi_pay/models/render_template_attributes'
require 'subfi_pay/models/render_template_create_request'
require 'subfi_pay/models/render_template_response'
require 'subfi_pay/models/setup_intent_confirm_attributes'
require 'subfi_pay/models/setup_intent_confirm_request'
require 'subfi_pay/models/setup_intent_create_attributes'
require 'subfi_pay/models/setup_intent_create_request'
require 'subfi_pay/models/setup_intent_response'
require 'subfi_pay/models/subscription_attributes'
require 'subfi_pay/models/subscription_create_request'
require 'subfi_pay/models/subscription_plan_attributes'
require 'subfi_pay/models/subscription_plan_create_request'
require 'subfi_pay/models/subscription_plan_response'
require 'subfi_pay/models/subscription_response'
require 'subfi_pay/models/token_response'
require 'subfi_pay/models/void_attributes'
require 'subfi_pay/models/void_response'
require 'subfi_pay/models/webhook_attempt_response'
require 'subfi_pay/models/webhook_endpoint_attributes'
require 'subfi_pay/models/webhook_endpoint_create_request'
require 'subfi_pay/models/webhook_endpoint_response'
require 'subfi_pay/models/webhook_request_response'

# APIs
require 'subfi_pay/api/accounts_api'
require 'subfi_pay/api/charges_api'
require 'subfi_pay/api/customers_api'
require 'subfi_pay/api/external_accounts_api'
require 'subfi_pay/api/merchants_api'
require 'subfi_pay/api/origins_api'
require 'subfi_pay/api/payment_intents_api'
require 'subfi_pay/api/payment_methods_api'
require 'subfi_pay/api/payouts_api'
require 'subfi_pay/api/processor_transactions_api'
require 'subfi_pay/api/products_api'
require 'subfi_pay/api/refunds_api'
require 'subfi_pay/api/render_templates_api'
require 'subfi_pay/api/setup_intents_api'
require 'subfi_pay/api/subscription_plans_api'
require 'subfi_pay/api/subscriptions_api'
require 'subfi_pay/api/voids_api'
require 'subfi_pay/api/webhook_attempts_api'
require 'subfi_pay/api/webhook_endpoints_api'
require 'subfi_pay/api/webhook_requests_api'

module SubfiPay
  class << self
    # Customize default settings for the SDK using block.
    #   SubfiPay.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
