=begin
#Subfi Pay API

#API for Subfi Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module SubfiPay
  class ChargeResponse
    attr_accessor :id

    attr_accessor :account_id

    attr_accessor :adjustment_reason

    attr_accessor :amount

    attr_accessor :currency

    attr_accessor :customer_id

    attr_accessor :description

    attr_accessor :allowed_reverse_action

    # Additional metadata key-value pairs
    attr_accessor :metadata

    attr_accessor :original_transaction_id

    attr_accessor :parent_transaction_id

    attr_accessor :payment_intent_id

    attr_accessor :payment_method_id

    attr_accessor :platform_fee

    attr_accessor :source

    attr_accessor :state

    attr_accessor :statement_descriptor

    attr_accessor :succeeded_at

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'account_id' => :'account_id',
        :'adjustment_reason' => :'adjustment_reason',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'customer_id' => :'customer_id',
        :'description' => :'description',
        :'allowed_reverse_action' => :'allowed_reverse_action',
        :'metadata' => :'metadata',
        :'original_transaction_id' => :'original_transaction_id',
        :'parent_transaction_id' => :'parent_transaction_id',
        :'payment_intent_id' => :'payment_intent_id',
        :'payment_method_id' => :'payment_method_id',
        :'platform_fee' => :'platform_fee',
        :'source' => :'source',
        :'state' => :'state',
        :'statement_descriptor' => :'statement_descriptor',
        :'succeeded_at' => :'succeeded_at',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'account_id' => :'String',
        :'adjustment_reason' => :'String',
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'customer_id' => :'String',
        :'description' => :'String',
        :'allowed_reverse_action' => :'String',
        :'metadata' => :'Hash<String, MetadataValue>',
        :'original_transaction_id' => :'String',
        :'parent_transaction_id' => :'String',
        :'payment_intent_id' => :'String',
        :'payment_method_id' => :'String',
        :'platform_fee' => :'Integer',
        :'source' => :'String',
        :'state' => :'String',
        :'statement_descriptor' => :'String',
        :'succeeded_at' => :'Time',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'allowed_reverse_action',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SubfiPay::ChargeResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SubfiPay::ChargeResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'adjustment_reason')
        self.adjustment_reason = attributes[:'adjustment_reason']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'allowed_reverse_action')
        self.allowed_reverse_action = attributes[:'allowed_reverse_action']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'original_transaction_id')
        self.original_transaction_id = attributes[:'original_transaction_id']
      end

      if attributes.key?(:'parent_transaction_id')
        self.parent_transaction_id = attributes[:'parent_transaction_id']
      end

      if attributes.key?(:'payment_intent_id')
        self.payment_intent_id = attributes[:'payment_intent_id']
      end

      if attributes.key?(:'payment_method_id')
        self.payment_method_id = attributes[:'payment_method_id']
      end

      if attributes.key?(:'platform_fee')
        self.platform_fee = attributes[:'platform_fee']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'statement_descriptor')
        self.statement_descriptor = attributes[:'statement_descriptor']
      end

      if attributes.key?(:'succeeded_at')
        self.succeeded_at = attributes[:'succeeded_at']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      allowed_reverse_action_validator = EnumAttributeValidator.new('String', ["void", "refund"])
      return false unless allowed_reverse_action_validator.valid?(@allowed_reverse_action)
      source_validator = EnumAttributeValidator.new('String', ["api", "dashboard", "iframe", "system", "subscription"])
      return false unless source_validator.valid?(@source)
      state_validator = EnumAttributeValidator.new('String', ["cancelled", "errored", "failed", "processing", "requires_capture", "requires_confirmation", "requires_review", "succeeded"])
      return false unless state_validator.valid?(@state)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] allowed_reverse_action Object to be assigned
    def allowed_reverse_action=(allowed_reverse_action)
      validator = EnumAttributeValidator.new('String', ["void", "refund"])
      unless validator.valid?(allowed_reverse_action)
        fail ArgumentError, "invalid value for \"allowed_reverse_action\", must be one of #{validator.allowable_values}."
      end
      @allowed_reverse_action = allowed_reverse_action
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source Object to be assigned
    def source=(source)
      validator = EnumAttributeValidator.new('String', ["api", "dashboard", "iframe", "system", "subscription"])
      unless validator.valid?(source)
        fail ArgumentError, "invalid value for \"source\", must be one of #{validator.allowable_values}."
      end
      @source = source
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["cancelled", "errored", "failed", "processing", "requires_capture", "requires_confirmation", "requires_review", "succeeded"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          account_id == o.account_id &&
          adjustment_reason == o.adjustment_reason &&
          amount == o.amount &&
          currency == o.currency &&
          customer_id == o.customer_id &&
          description == o.description &&
          allowed_reverse_action == o.allowed_reverse_action &&
          metadata == o.metadata &&
          original_transaction_id == o.original_transaction_id &&
          parent_transaction_id == o.parent_transaction_id &&
          payment_intent_id == o.payment_intent_id &&
          payment_method_id == o.payment_method_id &&
          platform_fee == o.platform_fee &&
          source == o.source &&
          state == o.state &&
          statement_descriptor == o.statement_descriptor &&
          succeeded_at == o.succeeded_at &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, account_id, adjustment_reason, amount, currency, customer_id, description, allowed_reverse_action, metadata, original_transaction_id, parent_transaction_id, payment_intent_id, payment_method_id, platform_fee, source, state, statement_descriptor, succeeded_at, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SubfiPay.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
