=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'cgi'

module BckbnPay
  class MerchantConfigurationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create merchant configurations
    # @param x_api_version [String] 
    # @param create_merchant_configuration_request [CreateMerchantConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [MerchantConfigurationResponse]
    def create_merchant_configurations(x_api_version, create_merchant_configuration_request, opts = {})
      data, _status_code, _headers = create_merchant_configurations_with_http_info(x_api_version, create_merchant_configuration_request, opts)
      data
    end

    # Create merchant configurations
    # @param x_api_version [String] 
    # @param create_merchant_configuration_request [CreateMerchantConfigurationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(MerchantConfigurationResponse, Integer, Hash)>] MerchantConfigurationResponse data, response status code and response headers
    def create_merchant_configurations_with_http_info(x_api_version, create_merchant_configuration_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MerchantConfigurationsApi.create_merchant_configurations ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling MerchantConfigurationsApi.create_merchant_configurations"
      end
      # verify the required parameter 'create_merchant_configuration_request' is set
      if @api_client.config.client_side_validation && create_merchant_configuration_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_merchant_configuration_request' when calling MerchantConfigurationsApi.create_merchant_configurations"
      end
      # resource path
      local_var_path = '/merchant_configurations'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
        header_params['Content-Type'] = content_type
      end
      header_params[:'X-Api-Version'] = x_api_version

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_merchant_configuration_request)

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantConfigurationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :operation => :"MerchantConfigurationsApi.create_merchant_configurations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MerchantConfigurationsApi#create_merchant_configurations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve merchant configurations
    # @param x_api_version [String] 
    # @param [Hash] opts the optional parameters
    # @return [MerchantConfigurationResponse]
    def get_merchant_configurations(x_api_version, opts = {})
      data, _status_code, _headers = get_merchant_configurations_with_http_info(x_api_version, opts)
      data
    end

    # Retrieve merchant configurations
    # @param x_api_version [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(MerchantConfigurationResponse, Integer, Hash)>] MerchantConfigurationResponse data, response status code and response headers
    def get_merchant_configurations_with_http_info(x_api_version, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MerchantConfigurationsApi.get_merchant_configurations ...'
      end
      # verify the required parameter 'x_api_version' is set
      if @api_client.config.client_side_validation && x_api_version.nil?
        fail ArgumentError, "Missing the required parameter 'x_api_version' when calling MerchantConfigurationsApi.get_merchant_configurations"
      end
      # resource path
      local_var_path = '/merchant_configurations'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      header_params[:'X-Api-Version'] = x_api_version

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantConfigurationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :operation => :"MerchantConfigurationsApi.get_merchant_configurations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MerchantConfigurationsApi#get_merchant_configurations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
