env:
  CI: true
  RAILS_ENV: test

name: Rubocop
on:
  push:

jobs:
  linter-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Bundle config & install
        run: bundle install

      - name: Rubocop linter
        run: bundle exec rubocop

